import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('metrika-language');
    return (saved as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('metrika-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['pt'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Traduções
const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navegação
    'nav.dashboard': 'Dashboard',
    'nav.trades': 'Trades',
    'nav.calendar': 'Calendário',
    'nav.charts': 'Gráficos',
    'nav.journal': 'Diário',
    'nav.brokers': 'Corretoras',
    'nav.profile': 'Perfil',
    'nav.admin': 'Admin',
    'nav.logout': 'Sair',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Visão Geral',
    'dashboard.total_balance': 'Saldo Total',
    'dashboard.monthly_result': 'Resultado Mensal',
    'dashboard.win_rate': 'Taxa de Acerto',
    'dashboard.total_trades': 'Total de Trades',
    'dashboard.avg_rr': 'R/R Médio',
    'dashboard.best_setup': 'Melhor Setup',
    'dashboard.worst_setup': 'Pior Setup',
    'dashboard.recent_trades': 'Trades Recentes',
    'dashboard.performance_chart': 'Gráfico de Performance',
    'dashboard.ai_insights': 'Insights da IA',
    'dashboard.trading_calendar': 'Calendário de Trading',
    'dashboard.best_trade': 'Melhor Trade',
    'dashboard.worst_trade': 'Pior Trade',
    'dashboard.frequent_emotion': 'Emoção Frequente',
    'dashboard.capital_curve': 'Curva de Capital',
    'dashboard.detailed_temporal_performance': 'Performance Temporal Detalhada',
    'dashboard.imports_and_trades': 'Histórico de Importações e Trades',
    'dashboard.consolidated_total': 'Resultado Total Consolidado',
    'dashboard.market_distribution': 'Distribuição por Mercado',

    // Tabs
    'tabs.imports': 'Importações',
    'tabs.consolidated': 'Consolidado',

    // Filtros de tempo
    'time.7_days': '7 Dias',
    'time.1_year': '1 Ano',
    'time.times': 'vezes',
    'time.trades_today': 'Trades Hoje',

    // Consolidação
    'consolidated.summary': 'Resumo Consolidado',
    'consolidated.market_analysis': 'Análise consolidada dos diferentes mercados',

    // Gráficos e Métricas
    'metrics.accumulated_profitability': 'Rentabilidade Acumulada',
    'metrics.period_result': 'Resultado do Período',
    'metrics.profits': '✅ Lucros',
    'metrics.losses': '❌ Perdas',
    'metrics.total_profits': 'Total de Lucros',
    'metrics.total_losses': 'Total de Perdas',
    'metrics.period_result_short': 'Resultado Período',
    'metrics.total_profitability': 'Rentabilidade Total',
    'metrics.general_result': 'Resultado geral',
    'metrics.profitability_chart': 'Gráfico de Rentabilidade ao Longo do Tempo',
    'metrics.result': 'Resultado',

    // Trades
    'trades.title': 'Trades',
    'trades.add_new': 'Novo Trade',
    'trades.symbol': 'Ativo',
    'trades.market': 'Mercado',
    'trades.setup': 'Setup',
    'trades.capital': 'Capital',
    'trades.stop': 'Stop',
    'trades.target': 'Alvo',
    'trades.result': 'Resultado',
    'trades.quantity': 'Quantidade',
    'trades.risk': 'Risco',
    'trades.type': 'Tipo',
    'trades.comment': 'Comentário',
    'trades.emotion': 'Emoção',
    'trades.entry_price': 'Preço Entrada',
    'trades.exit_price': 'Preço Saída',
    'trades.broker': 'Corretora',
    'trades.status': 'Status',
    'trades.date': 'Data/Hora',
    'trades.actions': 'Ações',
    'trades.edit': 'Editar',
    'trades.delete': 'Excluir',
    'trades.filter_all': 'Todos',
    'trades.no_trades': 'Nenhum trade encontrado',

    // Formulário de Trade
    'trade_form.title_add': 'Adicionar Trade',
    'trade_form.title_edit': 'Editar Trade',
    'trade_form.symbol_placeholder': 'Ex: BTCUSD, WINQ25',
    'trade_form.setup_placeholder': 'Ex: Breakout, Pullback',
    'trade_form.comment_placeholder': 'Observações sobre o trade',
    'trade_form.emotion_placeholder': 'Como você se sentiu',
    'trade_form.take_result': 'Take (ganho)',
    'trade_form.loss_result': 'Loss (perda)',
    'trade_form.save': 'Salvar Trade',
    'trade_form.cancel': 'Cancelar',
    'trade_form.validation_required': 'Campo obrigatório',
    'trade_form.validation_positive': 'Deve ser maior que zero',

    // Calendário
    'calendar.title': 'Calendário de Trading',
    'calendar.trades_count': 'trades',
    'calendar.win': 'win',
    'calendar.diary_entry': 'Entrada do Diário',
    'calendar.add_diary': 'Adicionar ao Diário',
    'calendar.edit_diary': 'Editar Diário',
    'calendar.how_to_use': 'Como Usar o Calendário',
    'calendar.profitable_days': 'Dias Lucrativos',
    'calendar.profitable_days_desc': 'Marcados com ponto verde, mostram o P&L positivo do dia',
    'calendar.loss_days': 'Dias com Prejuízo',
    'calendar.loss_days_desc': 'Marcados com ponto vermelho, mostram o P&L negativo do dia',
    'calendar.weekly_summary': 'Resumo Semanal',
    'calendar.weekly_summary_desc': 'Coluna lateral com totais consolidados por semana',
    'calendar.analysis_tips': 'Dicas de Análise',
    'calendar.temporal_patterns': '📈 Padrões Temporais',
    'calendar.improvement_strategies': '🎯 Estratégias de Melhoria',
    'calendar.tip1': 'Identifique quais dias da semana são mais lucrativos',
    'calendar.tip2': 'Observe se há padrões em sequências de wins/losses',
    'calendar.tip3': 'Analise a performance em diferentes semanas do mês',
    'calendar.tip4': 'Compare meses para identificar sazonalidade',
    'calendar.strategy1': 'Evite trading em dias consistentemente negativos',
    'calendar.strategy2': 'Aumente volume em dias/períodos mais lucrativos',
    'calendar.strategy3': 'Use breaks após sequências de perdas',
    'calendar.strategy4': 'Documente o que funcionou nos dias verdes',

    // Dias da semana abreviados
    'calendar.sun_short': 'Dom',
    'calendar.mon_short': 'Seg',
    'calendar.tue_short': 'Ter',
    'calendar.wed_short': 'Qua',
    'calendar.thu_short': 'Qui',
    'calendar.fri_short': 'Sex',
    'calendar.sat_short': 'Sáb',

    // Resumos e estatísticas
    'calendar.summary_of': 'Resumo de',
    'calendar.pnl_total': 'P&L Total',
    'calendar.day': 'dia',
    'calendar.days': 'dias',
    'calendar.week': 'Semana',
    'calendar.trading_days': 'Dias de Trading',
    'calendar.total_trades': 'Total de Trades',
    'calendar.win_rate': 'Taxa de Acerto',

    // Novo Trade e CSV
    'trade.manual': 'Manual',
    'trade.import_csv': 'Importar CSV',
    'trade.csv_file': 'Arquivo CSV',
    'trade.csv_format_by_market': 'Formato do CSV por Mercado',
    'trade.analyzing_ai': 'Analisando com IA...',
    'trade.import_with_ai': '🤖 Importar com IA',
    'trade.import_fast': '⚡ Importar Rápido',
    'trade.csv_rejected': '❌ Arquivo CSV rejeitado:',
    'trade.processing': 'Processando...',
    'trade.import_trades_csv': 'Importar Trades via CSV',
    'trade.select_csv_exported': 'Selecione um arquivo CSV exportado do seu mercado',
    'trade.analysis_complete': '✨ Análise Profunda Concluída',
    'trade.insights_generated': 'insights detalhados gerados! Visualize a análise completa na tela.',
    'trade.import_csv_first': 'Importe um arquivo CSV primeiro para usar a análise IA.',

    // Formulário de Trade Manual
    'form.trade_data': 'Dados da Operação',
    'form.date_time': 'Data e Hora',
    'form.asset': 'Ativo',
    'form.market': 'Mercado',
    'form.select_market': 'Selecione o mercado',
    'form.crypto': '₿ Crypto',
    'form.forex': '$ Forex',
    'form.b3': '▲ B3',
    'form.type': 'Tipo',
    'form.buy_or_sell': 'Compra ou Venda',
    'form.buy': 'Compra',
    'form.sell': 'Venda',
    'form.take_profit': 'Take Profit (valor de ganho)',
    'form.stop_loss': 'Stop Loss (valor de perda)',
    'form.trade_result': 'Resultado da Operação',
    'form.select_result_warning': '⚠️ Selecione o resultado para calcular o valor financeiro',
    'form.take': '◉ Take',
    'form.loss': '○ Loss',
    'form.auto_calculations': 'Cálculos Automáticos',
    'form.risk_reward_ratio': 'Razão Risco/Retorno',
    'form.financial_result': 'Resultado Financeiro',
    'form.excellent_ratio': '● Excelente (≥3:1)',
    'form.good_ratio': '▲ Bom (≥2:1)',
    'form.risky_ratio': '■ Arriscado (<2:1)',
    'form.emotion': 'Emoção Percebida',
    'form.how_felt': 'Como você se sentiu?',
    'form.trade_comment': 'Comentário sobre o Trade',
    'form.comment_placeholder': 'Descreva seu raciocínio, observações sobre o mercado, lições aprendidas...',
    'form.saving': 'Salvando...',
    'form.save_trade': 'Salvar Trade',
    'form.clear': 'Limpar',
    'form.analyze_ai': '🤖 Analisar com IA',
    'form.required_fields': 'Campos obrigatórios',
    'form.fill_required': 'Preencha pelo menos: Ativo, Mercado e Tipo para análise.',
    'form.select_market_label': 'Selecione o Mercado',
    'form.crypto_b3_forex': 'Crypto, B3 ou Forex',
    'form.crypto_icon': '🪙 Crypto',
    'form.b3_icon': '📈 B3',
    'form.forex_icon': '🏦 Forex',
    'form.analysis_method': 'Método de Análise',
    'form.choose_processing': 'Escolha o método de processamento',
    'form.ai_analysis': '🤖 Análise Por IA (Beta)',
    'form.traditional_analysis': '⚡ Análise MetrikAI (Recomendado)',
    'form.ai_description': '✨ IA: Mais inteligente, interpreta qualquer formato, mas pode ser mais lento',
    'form.traditional_description': '⚡ Tradicional: Mais rápido e consistente, ideal para formatos padrão',

    // Gráficos/Charts
    'charts.chart_settings': 'Configurações do Gráfico',
    'charts.market': 'Mercado',
    'charts.asset': 'Ativo',
    'charts.timeframe': 'Temporalidade',
    'charts.forex': 'Forex',
    'charts.crypto': 'Crypto',
    'charts.b3_stocks': 'B3 (Ações/Futuros)',
    'charts.current_asset': 'Ativo Atual:',
    'charts.current_timeframe': 'Temporalidade:',
    'charts.interval.1min': '1 minuto',
    'charts.interval.5min': '5 minutos',
    'charts.interval.15min': '15 minutos',
    'charts.interval.30min': '30 minutos',
    'charts.interval.1hour': '1 hora',
    'charts.interval.4hours': '4 horas',
    'charts.interval.daily': 'Diário',
    'charts.interval.weekly': 'Semanal',
    'charts.professional_chart': 'Gráfico profissional integrado',
    'charts.interval_label': 'Intervalo:',
    'charts.simulated_data': 'Dados em tempo real simulados',
    'charts.updated': 'Atualizado:',
    'charts.minutes': 'minutos',

    // Diário
    'journal.title': 'Diário de Trading',
    'journal.add_entry': 'Nova Entrada',
    'journal.date': 'Data',
    'journal.content': 'Conteúdo',
    'journal.mood': 'Humor',
    'journal.lessons': 'Lições Aprendidas',
    'journal.save': 'Salvar',
    'journal.cancel': 'Cancelar',

    // Corretoras
    'brokers.title': 'Corretoras',
    'brokers.csv_import': 'Importar CSV',
    'brokers.api_config': 'Configurar API',
    'brokers.manual_entry': 'Entrada Manual',

    // Perfil
    'profile.title': 'Perfil',
    'profile.personal_info': 'Informações Pessoais',
    'profile.subscription': 'Assinatura',
    'profile.settings': 'Configurações',

    // Formulários gerais
    'form.save': 'Salvar',
    'form.cancel': 'Cancelar',
    'form.delete': 'Excluir',
    'form.edit': 'Editar',
    'form.close': 'Fechar',
    'form.submit': 'Enviar',

    // Landing Page
    'landing.hero_title': 'A Plataforma Completa para Análise de Trading',
    'landing.hero_subtitle': 'Analise seus trades, controle suas emoções e evolua como trader com nossa plataforma alimentada por IA.',
    'landing.start_free': 'Começar Grátis',
    'landing.features': 'Funcionalidades',
    'landing.pricing': 'Preços',
    'landing.testimonials': 'Depoimentos',
    'landing.contact': 'Contato',
    'landing.header.features': 'Recursos',
    'landing.header.pricing': 'Preços',
    'landing.header.contact': 'Contato',
    'landing.header.login': 'Entrar',
    'landing.header.start': 'Começar Agora',
    'landing.hero.title1': 'O Fim das',
    'landing.hero.title2': 'Planilhas',
    'landing.hero.title3': 'de Trading',
    'landing.hero.subtitle': 'A única plataforma que analisa seus trades automaticamente e revela',
    'landing.hero.subtitle_highlight': 'os padrões que geram lucro',
    'landing.auto_import': 'Import automático de trades',
    'landing.ai_analysis': 'Análise IA + insights',
    'landing.real_charts': 'Gráficos reais TradingView',

    // Mensagens
    'messages.success': 'Sucesso!',
    'messages.error': 'Erro',
    'messages.loading': 'Carregando...',
    'messages.no_data': 'Nenhum dado encontrado',
    'messages.confirm_delete': 'Tem certeza que deseja excluir?',

    // Autenticação
    'auth.login': 'Entrar',
    'auth.register': 'Cadastrar',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.remember_me': 'Lembrar de mim',
    'auth.forgot_password': 'Esqueci minha senha',

    // Métricas e estatísticas
    'metrics.profitable_trades': 'Trades Lucrativos',
    'metrics.losing_trades': 'Trades Perdedores',
    'metrics.average_profit': 'Lucro Médio',
    'metrics.average_loss': 'Perda Média',
    'metrics.best_month': 'Melhor Mês',
    'metrics.worst_month': 'Pior Mês',
    'metrics.recovery_factor': 'Fator de Recuperação',
    'metrics.max_drawdown': 'Drawdown Máximo',
    'metrics.profit_factor': 'Fator de Lucro',

    // Períodos e datas
    'period.daily': 'Diário',
    'period.weekly': 'Semanal',
    'period.monthly': 'Mensal',
    'period.yearly': 'Anual',
    'period.all_time': 'Todo Período',

    // Status e ações
    'status.active': 'Ativo',
    'status.inactive': 'Inativo',
    'status.pending': 'Pendente',
    'status.completed': 'Concluído',
    'action.reset': 'Resetar',
    'action.import': 'Importar',
    'action.export': 'Exportar',
    'action.sync': 'Sincronizar',
    'action.refresh': 'Atualizar',

    // Corretoras e mercados
    'broker.forex.name': 'Forex',
    'broker.forex.type': 'Câmbio',
    'broker.forex.description': 'Trading Forex com importação CSV',
    'broker.b3.name': 'B3',
    'broker.b3.type': 'Ações BR',
    'broker.b3.description': 'Ações brasileiras B3 com importação CSV',
    'broker.crypto.name': 'Crypto',
    'broker.crypto.type': 'Criptomoedas',
    'broker.crypto.description': 'Trading de criptomoedas com importação CSV',

    // Setups de trading
    'setup.breakout': 'Breakout',
    'setup.pullback': 'Pullback',
    'setup.reversao': 'Reversão',
    'setup.tendencia': 'Tendência',
    'setup.support_resistance': 'Support/Resistance',
    'setup.fibonacci': 'Fibonacci',
    'setup.candlestick': 'Candlestick Pattern',
    'setup.divergencia': 'Divergência',
    'setup.scalping': 'Scalping',
    'setup.swing': 'Swing',

    // Emoções
    'emotion.confiante': 'Confiante',
    'emotion.ansioso': 'Ansioso',
    'emotion.impulsivo': 'Impulsivo',
    'emotion.calmo': 'Calmo',
    'emotion.euforico': 'Eufórico',
    'emotion.frustrado': 'Frustrado',
    'emotion.neutro': 'Neutro',

    // Labels de gráficos
    'chart.profitability_accumulated': 'Rentabilidade Acumulada',
    'chart.period_result': 'Resultado do Período',
    'chart.daily': 'Dia',
    'chart.weekly': 'Semana',
    'chart.monthly': 'Mês',
    'chart.yearly': 'Ano',
    'chart.all_months': 'Todos',
    'chart.specific_month': 'Mês Específico',
    'chart.select_month': 'Selecione o mês',

    // Períodos de tempo
    'time.day': 'Dia',
    'time.week': 'Semana',
    'time.month': 'Mês',
    'time.year': 'Ano',
    'time.all': 'Todos',

    // Placeholders e dicas
    'placeholder.select_month': 'Selecione o mês',
    'placeholder.select_option': 'Selecione uma opção',
    'placeholder.search': 'Pesquisar...',

    // Upload e importação
    'upload.csv_import': 'Importação CSV',
    'upload.select_file': 'Selecionar arquivo',
    'upload.analyzing': 'Analisando...',
    'upload.processing': 'Processando...',
    'upload.success': 'Sucesso!',
    'upload.error': 'Erro no upload',

    // Dias da semana
    'weekdays.sunday': 'Domingo',
    'weekdays.monday': 'Segunda',
    'weekdays.tuesday': 'Terça',
    'weekdays.wednesday': 'Quarta',
    'weekdays.thursday': 'Quinta',
    'weekdays.friday': 'Sexta',
    'weekdays.saturday': 'Sábado',

    // Mensagens de estado vazio
    'empty.no_trades_period': 'Nenhum trade no período selecionado',
    'empty.no_manual_trades': 'Nenhum trade manual criado ainda',
  },

  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.trades': 'Trades',
    'nav.calendar': 'Calendar',
    'nav.charts': 'Charts',
    'nav.journal': 'Journal',
    'nav.brokers': 'Brokers',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Overview',
    'dashboard.total_balance': 'Total Balance',
    'dashboard.monthly_result': 'Monthly Result',
    'dashboard.win_rate': 'Win Rate',
    'dashboard.total_trades': 'Total Trades',
    'dashboard.avg_rr': 'Avg R/R',
    'dashboard.best_setup': 'Best Setup',
    'dashboard.worst_setup': 'Worst Setup',
    'dashboard.recent_trades': 'Recent Trades',
    'dashboard.performance_chart': 'Performance Chart',
    'dashboard.ai_insights': 'AI Insights',
    'dashboard.trading_calendar': 'Trading Calendar',
    'dashboard.best_trade': 'Best Trade',
    'dashboard.worst_trade': 'Worst Trade',
    'dashboard.frequent_emotion': 'Frequent Emotion',
    'dashboard.capital_curve': 'Capital Curve',
    'dashboard.detailed_temporal_performance': 'Detailed Temporal Performance',
    'dashboard.imports_and_trades': 'Imports and Trades History',
    'dashboard.consolidated_total': 'Total Consolidated Result',
    'dashboard.market_distribution': 'Market Distribution',

    // Tabs
    'tabs.imports': 'Imports',
    'tabs.consolidated': 'Consolidated',

    // Time filters
    'time.7_days': '7 Days',
    'time.1_year': '1 Year',
    'time.times': 'times',
    'time.trades_today': 'Trades Today',

    // Consolidation
    'consolidated.summary': 'Consolidated Summary',
    'consolidated.market_analysis': 'Consolidated analysis of different markets',

    // Charts and Metrics
    'metrics.accumulated_profitability': 'Accumulated Profitability',
    'metrics.period_result': 'Period Result',
    'metrics.profits': '✅ Profits',
    'metrics.losses': '❌ Losses',
    'metrics.total_profits': 'Total Profits',
    'metrics.total_losses': 'Total Losses',
    'metrics.period_result_short': 'Period Result',
    'metrics.total_profitability': 'Total Profitability',
    'metrics.general_result': 'General result',
    'metrics.profitability_chart': 'Profitability Chart Over Time',
    'metrics.result': 'Result',

    // Trades
    'trades.title': 'Trades',
    'trades.add_new': 'New Trade',
    'trades.symbol': 'Symbol',
    'trades.market': 'Market',
    'trades.setup': 'Setup',
    'trades.capital': 'Capital',
    'trades.stop': 'Stop',
    'trades.target': 'Target',
    'trades.result': 'Result',
    'trades.quantity': 'Quantity',
    'trades.risk': 'Risk',
    'trades.type': 'Type',
    'trades.comment': 'Comment',
    'trades.emotion': 'Emotion',
    'trades.entry_price': 'Entry Price',
    'trades.exit_price': 'Exit Price',
    'trades.broker': 'Broker',
    'trades.status': 'Status',
    'trades.date': 'Date/Time',
    'trades.actions': 'Actions',
    'trades.edit': 'Edit',
    'trades.delete': 'Delete',
    'trades.filter_all': 'All',
    'trades.no_trades': 'No trades found',

    // Trade Form
    'trade_form.title_add': 'Add Trade',
    'trade_form.title_edit': 'Edit Trade',
    'trade_form.symbol_placeholder': 'e.g., BTCUSD, EURUSD',
    'trade_form.setup_placeholder': 'e.g., Breakout, Pullback',
    'trade_form.comment_placeholder': 'Trade observations',
    'trade_form.emotion_placeholder': 'How did you feel',
    'trade_form.take_result': 'Take (profit)',
    'trade_form.loss_result': 'Loss',
    'trade_form.save': 'Save Trade',
    'trade_form.cancel': 'Cancel',
    'trade_form.validation_required': 'Required field',
    'trade_form.validation_positive': 'Must be greater than zero',

    // Calendar
    'calendar.title': 'Trading Calendar',
    'calendar.trades_count': 'trades',
    'calendar.win': 'win',
    'calendar.diary_entry': 'Diary Entry',
    'calendar.add_diary': 'Add to Diary',
    'calendar.edit_diary': 'Edit Diary',
    'calendar.how_to_use': 'How to Use Calendar',
    'calendar.profitable_days': 'Profitable Days',
    'calendar.profitable_days_desc': 'Marked with green dot, show positive P&L for the day',
    'calendar.loss_days': 'Loss Days',
    'calendar.loss_days_desc': 'Marked with red dot, show negative P&L for the day',
    'calendar.weekly_summary': 'Weekly Summary',
    'calendar.weekly_summary_desc': 'Side column with consolidated weekly totals',
    'calendar.analysis_tips': 'Analysis Tips',
    'calendar.temporal_patterns': '📈 Temporal Patterns',
    'calendar.improvement_strategies': '🎯 Improvement Strategies',
    'calendar.tip1': 'Identify which days of the week are most profitable',
    'calendar.tip2': 'Observe patterns in win/loss sequences',
    'calendar.tip3': 'Analyze performance across different weeks of the month',
    'calendar.tip4': 'Compare months to identify seasonality',
    'calendar.strategy1': 'Avoid trading on consistently negative days',
    'calendar.strategy2': 'Increase volume on more profitable days/periods',
    'calendar.strategy3': 'Take breaks after losing streaks',
    'calendar.strategy4': 'Document what worked on green days',

    // Abbreviated weekdays
    'calendar.sun_short': 'Sun',
    'calendar.mon_short': 'Mon',
    'calendar.tue_short': 'Tue',
    'calendar.wed_short': 'Wed',
    'calendar.thu_short': 'Thu',
    'calendar.fri_short': 'Fri',
    'calendar.sat_short': 'Sat',

    // Summaries and statistics
    'calendar.summary_of': 'Summary of',
    'calendar.pnl_total': 'Total P&L',
    'calendar.day': 'day',
    'calendar.days': 'days',
    'calendar.week': 'Week',
    'calendar.trading_days': 'Trading Days',
    'calendar.total_trades': 'Total Trades',
    'calendar.win_rate': 'Win Rate',

    // New Trade and CSV
    'trade.manual': 'Manual',
    'trade.import_csv': 'Import CSV',
    'trade.csv_file': 'CSV File',
    'trade.csv_format_by_market': 'CSV Format by Market',
    'trade.analyzing_ai': 'Analyzing with AI...',
    'trade.import_with_ai': '🤖 Import with AI',
    'trade.import_fast': '⚡ Import Fast',
    'trade.csv_rejected': '❌ CSV file rejected:',
    'trade.processing': 'Processing...',
    'trade.import_trades_csv': 'Import Trades via CSV',
    'trade.select_csv_exported': 'Select a CSV file exported from your market',
    'trade.analysis_complete': '✨ Deep Analysis Complete',
    'trade.insights_generated': 'detailed insights generated! View the complete analysis on screen.',
    'trade.import_csv_first': 'Import a CSV file first to use AI analysis.',

    // Manual Trade Form
    'form.trade_data': 'Trade Data',
    'form.date_time': 'Date and Time',
    'form.asset': 'Asset',
    'form.market': 'Market',
    'form.select_market': 'Select market',
    'form.crypto': '₿ Crypto',
    'form.forex': '$ Forex',
    'form.b3': '▲ B3',
    'form.type': 'Type',
    'form.buy_or_sell': 'Buy or Sell',
    'form.buy': 'Buy',
    'form.sell': 'Sell',
    'form.take_profit': 'Take Profit (gain value)',
    'form.stop_loss': 'Stop Loss (loss value)',
    'form.trade_result': 'Trade Result',
    'form.select_result_warning': '⚠️ Select result to calculate financial value',
    'form.take': '◉ Take',
    'form.loss': '○ Loss',
    'form.auto_calculations': 'Automatic Calculations',
    'form.risk_reward_ratio': 'Risk/Reward Ratio',
    'form.financial_result': 'Financial Result',
    'form.excellent_ratio': '● Excellent (≥3:1)',
    'form.good_ratio': '▲ Good (≥2:1)',
    'form.risky_ratio': '■ Risky (<2:1)',
    'form.emotion': 'Perceived Emotion',
    'form.how_felt': 'How did you feel?',
    'form.trade_comment': 'Trade Comment',
    'form.comment_placeholder': 'Describe your reasoning, market observations, lessons learned...',
    'form.saving': 'Saving...',
    'form.save_trade': 'Save Trade',
    'form.clear': 'Clear',
    'form.analyze_ai': '🤖 Analyze with AI',
    'form.required_fields': 'Required fields',
    'form.fill_required': 'Fill at least: Asset, Market and Type for analysis.',
    'form.select_market_label': 'Select Market',
    'form.crypto_b3_forex': 'Crypto, B3 or Forex',
    'form.crypto_icon': '🪙 Crypto',
    'form.b3_icon': '📈 B3',
    'form.forex_icon': '🏦 Forex',
    'form.analysis_method': 'Analysis Method',
    'form.choose_processing': 'Choose processing method',
    'form.ai_analysis': '🤖 AI Analysis (Beta)',
    'form.traditional_analysis': '⚡ MetrikAI Analysis (Recommended)',
    'form.ai_description': '✨ AI: Smarter, interprets any format, but may be slower',
    'form.traditional_description': '⚡ Traditional: Faster and consistent, ideal for standard formats',

    // Charts
    'charts.chart_settings': 'Chart Settings',
    'charts.market': 'Market',
    'charts.asset': 'Asset',
    'charts.timeframe': 'Timeframe',
    'charts.forex': 'Forex',
    'charts.crypto': 'Crypto',
    'charts.b3_stocks': 'B3 (Stocks/Futures)',
    'charts.current_asset': 'Current Asset:',
    'charts.current_timeframe': 'Timeframe:',
    'charts.interval.1min': '1 minute',
    'charts.interval.5min': '5 minutes',
    'charts.interval.15min': '15 minutes',
    'charts.interval.30min': '30 minutes',
    'charts.interval.1hour': '1 hour',
    'charts.interval.4hours': '4 hours',
    'charts.interval.daily': 'Daily',
    'charts.interval.weekly': 'Weekly',
    'charts.professional_chart': 'Professional integrated chart',
    'charts.interval_label': 'Interval:',
    'charts.simulated_data': 'Real-time simulated data',
    'charts.updated': 'Updated:',
    'charts.minutes': 'minutes',

    // Journal
    'journal.title': 'Trading Journal',
    'journal.add_entry': 'New Entry',
    'journal.date': 'Date',
    'journal.content': 'Content',
    'journal.mood': 'Mood',
    'journal.lessons': 'Lessons Learned',
    'journal.save': 'Save',
    'journal.cancel': 'Cancel',

    // Brokers
    'brokers.title': 'Brokers',
    'brokers.csv_import': 'Import CSV',
    'brokers.api_config': 'API Config',
    'brokers.manual_entry': 'Manual Entry',

    // Profile
    'profile.title': 'Profile',
    'profile.personal_info': 'Personal Information',
    'profile.subscription': 'Subscription',
    'profile.settings': 'Settings',

    // General Forms
    'form.save': 'Save',
    'form.cancel': 'Cancel',
    'form.delete': 'Delete',
    'form.edit': 'Edit',
    'form.close': 'Close',
    'form.submit': 'Submit',

    // Landing Page
    'landing.hero_title': 'The Complete Platform for Trading Analysis',
    'landing.hero_subtitle': 'Analyze your trades, control your emotions, and evolve as a trader with our AI-powered platform.',
    'landing.start_free': 'Start Free',
    'landing.features': 'Features',
    'landing.pricing': 'Pricing',
    'landing.testimonials': 'Testimonials',
    'landing.contact': 'Contact',
    'landing.header.features': 'Features',
    'landing.header.pricing': 'Pricing',
    'landing.header.contact': 'Contact',
    'landing.header.login': 'Login',
    'landing.header.start': 'Get Started',
    'landing.hero.title1': 'The End of',
    'landing.hero.title2': 'Trading',
    'landing.hero.title3': 'Spreadsheets',
    'landing.hero.subtitle': 'The only platform that analyzes your trades automatically and reveals',
    'landing.hero.subtitle_highlight': 'the patterns that generate profit',
    'landing.auto_import': 'Automatic trade import',
    'landing.ai_analysis': 'AI analysis + insights',
    'landing.real_charts': 'Real TradingView charts',

    // Messages
    'messages.success': 'Success!',
    'messages.error': 'Error',
    'messages.loading': 'Loading...',
    'messages.no_data': 'No data found',
    'messages.confirm_delete': 'Are you sure you want to delete?',

    // Authentication
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.remember_me': 'Remember me',
    'auth.forgot_password': 'Forgot password',

    // Metrics and statistics
    'metrics.profitable_trades': 'Profitable Trades',
    'metrics.losing_trades': 'Losing Trades',
    'metrics.average_profit': 'Average Profit',
    'metrics.average_loss': 'Average Loss',
    'metrics.best_month': 'Best Month',
    'metrics.worst_month': 'Worst Month',
    'metrics.recovery_factor': 'Recovery Factor',
    'metrics.max_drawdown': 'Max Drawdown',
    'metrics.profit_factor': 'Profit Factor',

    // Periods and dates
    'period.daily': 'Daily',
    'period.weekly': 'Weekly',
    'period.monthly': 'Monthly',
    'period.yearly': 'Yearly',
    'period.all_time': 'All Time',

    // Status and actions
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.completed': 'Completed',
    'action.reset': 'Reset',
    'action.import': 'Import',
    'action.export': 'Export',
    'action.sync': 'Sync',
    'action.refresh': 'Refresh',

    // Brokers and markets
    'broker.forex.name': 'Forex',
    'broker.forex.type': 'Currency',
    'broker.forex.description': 'Forex trading with CSV import',
    'broker.b3.name': 'B3',
    'broker.b3.type': 'BR Stocks',
    'broker.b3.description': 'Brazilian B3 stocks with CSV import',
    'broker.crypto.name': 'Crypto',
    'broker.crypto.type': 'Cryptocurrencies',
    'broker.crypto.description': 'Cryptocurrency trading with CSV import',

    // Trading setups
    'setup.breakout': 'Breakout',
    'setup.pullback': 'Pullback',
    'setup.reversao': 'Reversal',
    'setup.tendencia': 'Trend',
    'setup.support_resistance': 'Support/Resistance',
    'setup.fibonacci': 'Fibonacci',
    'setup.candlestick': 'Candlestick Pattern',
    'setup.divergencia': 'Divergence',
    'setup.scalping': 'Scalping',
    'setup.swing': 'Swing',

    // Emotions
    'emotion.confiante': 'Confident',
    'emotion.ansioso': 'Anxious',
    'emotion.impulsivo': 'Impulsive',
    'emotion.calmo': 'Calm',
    'emotion.euforico': 'Euphoric',
    'emotion.frustrado': 'Frustrated',
    'emotion.neutro': 'Neutral',

    // Chart labels
    'chart.profitability_accumulated': 'Accumulated Profitability',
    'chart.period_result': 'Period Result',
    'chart.daily': 'Day',
    'chart.weekly': 'Week',
    'chart.monthly': 'Month',
    'chart.yearly': 'Year',
    'chart.all_months': 'All',
    'chart.specific_month': 'Specific Month',
    'chart.select_month': 'Select month',

    // Time periods
    'time.day': 'Day',
    'time.week': 'Week',
    'time.month': 'Month',
    'time.year': 'Year',
    'time.all': 'All',

    // Placeholders and hints
    'placeholder.select_month': 'Select month',
    'placeholder.select_option': 'Select an option',
    'placeholder.search': 'Search...',

    // Upload and import
    'upload.csv_import': 'CSV Import',
    'upload.select_file': 'Select file',
    'upload.analyzing': 'Analyzing...',
    'upload.processing': 'Processing...',
    'upload.success': 'Success!',
    'upload.error': 'Upload error',

    // Weekdays
    'weekdays.sunday': 'Sunday',
    'weekdays.monday': 'Monday',
    'weekdays.tuesday': 'Tuesday',
    'weekdays.wednesday': 'Wednesday',
    'weekdays.thursday': 'Thursday',
    'weekdays.friday': 'Friday',
    'weekdays.saturday': 'Saturday',

    // Empty state messages
    'empty.no_trades_period': 'No trades in selected period',
    'empty.no_manual_trades': 'No manual trades created yet',
  },

  es: {
    // Navegación
    'nav.dashboard': 'Panel',
    'nav.trades': 'Operaciones',
    'nav.calendar': 'Calendario',
    'nav.charts': 'Gráficos',
    'nav.journal': 'Diario',
    'nav.brokers': 'Brokers',
    'nav.profile': 'Perfil',
    'nav.admin': 'Admin',
    'nav.logout': 'Salir',

    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.overview': 'Resumen',
    'dashboard.total_balance': 'Saldo Total',
    'dashboard.monthly_result': 'Resultado Mensual',
    'dashboard.win_rate': 'Tasa de Acierto',
    'dashboard.total_trades': 'Total Operaciones',
    'dashboard.avg_rr': 'R/R Promedio',
    'dashboard.best_setup': 'Mejor Setup',
    'dashboard.worst_setup': 'Peor Setup',
    'dashboard.recent_trades': 'Operaciones Recientes',
    'dashboard.performance_chart': 'Gráfico de Rendimiento',
    'dashboard.ai_insights': 'Insights de IA',
    'dashboard.trading_calendar': 'Calendario de Trading',
    'dashboard.best_trade': 'Mejor Operación',
    'dashboard.worst_trade': 'Peor Operación',
    'dashboard.frequent_emotion': 'Emoción Frecuente',
    'dashboard.capital_curve': 'Curva de Capital',
    'dashboard.detailed_temporal_performance': 'Rendimiento Temporal Detallado',
    'dashboard.imports_and_trades': 'Historial de Importaciones y Operaciones',
    'dashboard.consolidated_total': 'Resultado Total Consolidado',
    'dashboard.market_distribution': 'Distribución por Mercado',

    // Tabs
    'tabs.imports': 'Importaciones',
    'tabs.consolidated': 'Consolidado',

    // Filtros de tiempo
    'time.7_days': '7 Días',
    'time.1_year': '1 Año',
    'time.times': 'veces',
    'time.trades_today': 'Operaciones Hoy',

    // Consolidación
    'consolidated.summary': 'Resumen Consolidado',
    'consolidated.market_analysis': 'Análisis consolidado de diferentes mercados',

    // Gráficos y Métricas
    'metrics.accumulated_profitability': 'Rentabilidad Acumulada',
    'metrics.period_result': 'Resultado del Período',
    'metrics.profits': '✅ Ganancias',
    'metrics.losses': '❌ Pérdidas',
    'metrics.total_profits': 'Total Ganancias',
    'metrics.total_losses': 'Total Pérdidas',
    'metrics.period_result_short': 'Resultado Período',
    'metrics.total_profitability': 'Rentabilidad Total',
    'metrics.general_result': 'Resultado general',
    'metrics.profitability_chart': 'Gráfico de Rentabilidad en el Tiempo',
    'metrics.result': 'Resultado',

    // Trades
    'trades.title': 'Operaciones',
    'trades.add_new': 'Nueva Operación',
    'trades.symbol': 'Símbolo',
    'trades.market': 'Mercado',
    'trades.setup': 'Setup',
    'trades.capital': 'Capital',
    'trades.stop': 'Stop',
    'trades.target': 'Objetivo',
    'trades.result': 'Resultado',
    'trades.quantity': 'Cantidad',
    'trades.risk': 'Riesgo',
    'trades.type': 'Tipo',
    'trades.comment': 'Comentario',
    'trades.emotion': 'Emoción',
    'trades.entry_price': 'Precio Entrada',
    'trades.exit_price': 'Precio Salida',
    'trades.broker': 'Broker',
    'trades.status': 'Estado',
    'trades.date': 'Fecha/Hora',
    'trades.actions': 'Acciones',
    'trades.edit': 'Editar',
    'trades.delete': 'Eliminar',
    'trades.filter_all': 'Todos',
    'trades.no_trades': 'No se encontraron operaciones',

    // Formulario de Trade
    'trade_form.title_add': 'Agregar Operación',
    'trade_form.title_edit': 'Editar Operación',
    'trade_form.symbol_placeholder': 'ej: BTCUSD, EURUSD',
    'trade_form.setup_placeholder': 'ej: Breakout, Pullback',
    'trade_form.comment_placeholder': 'Observaciones de la operación',
    'trade_form.emotion_placeholder': 'Cómo te sentiste',
    'trade_form.take_result': 'Take (ganancia)',
    'trade_form.loss_result': 'Loss (pérdida)',
    'trade_form.save': 'Guardar Operación',
    'trade_form.cancel': 'Cancelar',
    'trade_form.validation_required': 'Campo requerido',
    'trade_form.validation_positive': 'Debe ser mayor que cero',

    // Calendario
    'calendar.title': 'Calendario de Trading',
    'calendar.trades_count': 'operaciones',
    'calendar.win': 'acierto',
    'calendar.diary_entry': 'Entrada del Diario',
    'calendar.add_diary': 'Agregar al Diario',
    'calendar.edit_diary': 'Editar Diario',
    'calendar.how_to_use': 'Cómo Usar el Calendario',
    'calendar.profitable_days': 'Días Rentables',
    'calendar.profitable_days_desc': 'Marcados con punto verde, muestran P&L positivo del día',
    'calendar.loss_days': 'Días con Pérdidas',
    'calendar.loss_days_desc': 'Marcados con punto rojo, muestran P&L negativo del día',
    'calendar.weekly_summary': 'Resumen Semanal',
    'calendar.weekly_summary_desc': 'Columna lateral con totales consolidados por semana',
    'calendar.analysis_tips': 'Consejos de Análisis',
    'calendar.temporal_patterns': '📈 Patrones Temporales',
    'calendar.improvement_strategies': '🎯 Estrategias de Mejora',
    'calendar.tip1': 'Identifica qué días de la semana son más rentables',
    'calendar.tip2': 'Observa patrones en secuencias de aciertos/fallos',
    'calendar.tip3': 'Analiza el rendimiento en diferentes semanas del mes',
    'calendar.tip4': 'Compara meses para identificar estacionalidad',
    'calendar.strategy1': 'Evita trading en días consistentemente negativos',
    'calendar.strategy2': 'Aumenta volumen en días/períodos más rentables',
    'calendar.strategy3': 'Usa descansos después de secuencias de pérdidas',
    'calendar.strategy4': 'Documenta lo que funcionó en los días verdes',

    // Días de la semana abreviados
    'calendar.sun_short': 'Dom',
    'calendar.mon_short': 'Lun',
    'calendar.tue_short': 'Mar',
    'calendar.wed_short': 'Mié',
    'calendar.thu_short': 'Jue',
    'calendar.fri_short': 'Vie',
    'calendar.sat_short': 'Sáb',

    // Resúmenes y estadísticas
    'calendar.summary_of': 'Resumen de',
    'calendar.pnl_total': 'P&L Total',
    'calendar.day': 'día',
    'calendar.days': 'días',
    'calendar.week': 'Semana',
    'calendar.trading_days': 'Días de Trading',
    'calendar.total_trades': 'Total Operaciones',
    'calendar.win_rate': 'Tasa de Acierto',

    // Nuevo Trade y CSV
    'trade.manual': 'Manual',
    'trade.import_csv': 'Importar CSV',
    'trade.csv_file': 'Archivo CSV',
    'trade.csv_format_by_market': 'Formato CSV por Mercado',
    'trade.analyzing_ai': 'Analizando con IA...',
    'trade.import_with_ai': '🤖 Importar con IA',
    'trade.import_fast': '⚡ Importar Rápido',
    'trade.csv_rejected': '❌ Archivo CSV rechazado:',
    'trade.processing': 'Procesando...',
    'trade.import_trades_csv': 'Importar Operaciones vía CSV',
    'trade.select_csv_exported': 'Selecciona un archivo CSV exportado de tu mercado',
    'trade.analysis_complete': '✨ Análisis Profundo Completo',
    'trade.insights_generated': 'insights detallados generados! Visualiza el análisis completo en pantalla.',
    'trade.import_csv_first': 'Importa un archivo CSV primero para usar el análisis IA.',

    // Formulario de Operación Manual
    'form.trade_data': 'Datos de la Operación',
    'form.date_time': 'Fecha y Hora',
    'form.asset': 'Activo',
    'form.market': 'Mercado',
    'form.select_market': 'Selecciona mercado',
    'form.crypto': '₿ Crypto',
    'form.forex': '$ Forex',
    'form.b3': '▲ B3',
    'form.type': 'Tipo',
    'form.buy_or_sell': 'Compra o Venta',
    'form.buy': 'Compra',
    'form.sell': 'Venta',
    'form.take_profit': 'Take Profit (valor de ganancia)',
    'form.stop_loss': 'Stop Loss (valor de pérdida)',
    'form.trade_result': 'Resultado de la Operación',
    'form.select_result_warning': '⚠️ Selecciona el resultado para calcular el valor financiero',
    'form.take': '◉ Take',
    'form.loss': '○ Loss',
    'form.auto_calculations': 'Cálculos Automáticos',
    'form.risk_reward_ratio': 'Razón Riesgo/Recompensa',
    'form.financial_result': 'Resultado Financiero',
    'form.excellent_ratio': '● Excelente (≥3:1)',
    'form.good_ratio': '▲ Bueno (≥2:1)',
    'form.risky_ratio': '■ Arriesgado (<2:1)',
    'form.emotion': 'Emoción Percibida',
    'form.how_felt': '¿Cómo te sentiste?',
    'form.trade_comment': 'Comentario sobre la Operación',
    'form.comment_placeholder': 'Describe tu razonamiento, observaciones del mercado, lecciones aprendidas...',
    'form.saving': 'Guardando...',
    'form.save_trade': 'Guardar Operación',
    'form.clear': 'Limpiar',
    'form.analyze_ai': '🤖 Analizar con IA',
    'form.required_fields': 'Campos requeridos',
    'form.fill_required': 'Completa al menos: Activo, Mercado y Tipo para análisis.',
    'form.select_market_label': 'Seleccionar Mercado',
    'form.crypto_b3_forex': 'Crypto, B3 o Forex',
    'form.crypto_icon': '🪙 Crypto',
    'form.b3_icon': '📈 B3',
    'form.forex_icon': '🏦 Forex',
    'form.analysis_method': 'Método de Análisis',
    'form.choose_processing': 'Elige método de procesamiento',
    'form.ai_analysis': '🤖 Análisis por IA (Beta)',
    'form.traditional_analysis': '⚡ Análisis MetrikAI (Recomendado)',
    'form.ai_description': '✨ IA: Más inteligente, interpreta cualquier formato, pero puede ser más lento',
    'form.traditional_description': '⚡ Tradicional: Más rápido y consistente, ideal para formatos estándar',

    // Gráficos
    'charts.chart_settings': 'Configuración de Gráficos',
    'charts.market': 'Mercado',
    'charts.asset': 'Activo',
    'charts.timeframe': 'Marco Temporal',
    'charts.forex': 'Forex',
    'charts.crypto': 'Crypto',
    'charts.b3_stocks': 'B3 (Acciones/Futuros)',
    'charts.current_asset': 'Activo Actual:',
    'charts.current_timeframe': 'Marco Temporal:',
    'charts.interval.1min': '1 minuto',
    'charts.interval.5min': '5 minutos',
    'charts.interval.15min': '15 minutos',
    'charts.interval.30min': '30 minutos',
    'charts.interval.1hour': '1 hora',
    'charts.interval.4hours': '4 horas',
    'charts.interval.daily': 'Diario',
    'charts.interval.weekly': 'Semanal',
    'charts.professional_chart': 'Gráfico profesional integrado',
    'charts.interval_label': 'Intervalo:',
    'charts.simulated_data': 'Datos en tiempo real simulados',
    'charts.updated': 'Actualizado:',
    'charts.minutes': 'minutos',

    // Diario
    'journal.title': 'Diario de Trading',
    'journal.add_entry': 'Nueva Entrada',
    'journal.date': 'Fecha',
    'journal.content': 'Contenido',
    'journal.mood': 'Estado de Ánimo',
    'journal.lessons': 'Lecciones Aprendidas',
    'journal.save': 'Guardar',
    'journal.cancel': 'Cancelar',

    // Brokers
    'brokers.title': 'Brokers',
    'brokers.csv_import': 'Importar CSV',
    'brokers.api_config': 'Configurar API',
    'brokers.manual_entry': 'Entrada Manual',

    // Perfil
    'profile.title': 'Perfil',
    'profile.personal_info': 'Información Personal',
    'profile.subscription': 'Suscripción',
    'profile.settings': 'Configuraciones',

    // Formularios generales
    'form.save': 'Guardar',
    'form.cancel': 'Cancelar',
    'form.delete': 'Eliminar',
    'form.edit': 'Editar',
    'form.close': 'Cerrar',
    'form.submit': 'Enviar',

    // Landing Page
    'landing.hero_title': 'La Plataforma Completa para Análisis de Trading',
    'landing.hero_subtitle': 'Analiza tus operaciones, controla tus emociones y evoluciona como trader con nuestra plataforma potenciada por IA.',
    'landing.start_free': 'Comenzar Gratis',
    'landing.features': 'Características',
    'landing.pricing': 'Precios',
    'landing.testimonials': 'Testimonios',
    'landing.contact': 'Contacto',
    'landing.header.features': 'Características',
    'landing.header.pricing': 'Precios',
    'landing.header.contact': 'Contacto',
    'landing.header.login': 'Iniciar Sesión',
    'landing.header.start': 'Comenzar Ahora',
    'landing.hero.title1': 'El Fin de las',
    'landing.hero.title2': 'Hojas de Cálculo',
    'landing.hero.title3': 'de Trading',
    'landing.hero.subtitle': 'La única plataforma que analiza tus operaciones automáticamente y revela',
    'landing.hero.subtitle_highlight': 'los patrones que generan ganancias',
    'landing.auto_import': 'Importación automática de trades',
    'landing.ai_analysis': 'Análisis IA + insights',
    'landing.real_charts': 'Gráficos reales TradingView',

    // Mensajes
    'messages.success': '¡Éxito!',
    'messages.error': 'Error',
    'messages.loading': 'Cargando...',
    'messages.no_data': 'No se encontraron datos',
    'messages.confirm_delete': '¿Estás seguro de que quieres eliminar?',

    // Autenticación
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.remember_me': 'Recordarme',
    'auth.forgot_password': 'Olvidé mi contraseña',

    // Métricas y estadísticas
    'metrics.profitable_trades': 'Operaciones Rentables',
    'metrics.losing_trades': 'Operaciones Perdedoras',
    'metrics.average_profit': 'Ganancia Promedio',
    'metrics.average_loss': 'Pérdida Promedio',
    'metrics.best_month': 'Mejor Mes',
    'metrics.worst_month': 'Peor Mes',
    'metrics.recovery_factor': 'Factor de Recuperación',
    'metrics.max_drawdown': 'Drawdown Máximo',
    'metrics.profit_factor': 'Factor de Ganancia',

    // Períodos y fechas
    'period.daily': 'Diario',
    'period.weekly': 'Semanal',
    'period.monthly': 'Mensual',
    'period.yearly': 'Anual',
    'period.all_time': 'Todo el Tiempo',

    // Estado y acciones
    'status.active': 'Activo',
    'status.inactive': 'Inactivo',
    'status.pending': 'Pendiente',
    'status.completed': 'Completado',
    'action.reset': 'Resetear',
    'action.import': 'Importar',
    'action.export': 'Exportar',
    'action.sync': 'Sincronizar',
    'action.refresh': 'Actualizar',

    // Días de la semana
    'weekdays.sunday': 'Domingo',
    'weekdays.monday': 'Lunes',
    'weekdays.tuesday': 'Martes',
    'weekdays.wednesday': 'Miércoles',
    'weekdays.thursday': 'Jueves',
    'weekdays.friday': 'Viernes',
    'weekdays.saturday': 'Sábado',

    // Mensajes de estado vacío
    'empty.no_trades_period': 'Ninguna operación en el período seleccionado',
    'empty.no_manual_trades': 'Ninguna operación manual creada aún',
  }
};